language: go

sudo: required

go:
  - 1.8
  - 1.9

services:
  - postgresql
  - docker

env:
  - DEX_POSTGRES_DATABASE=postgres DEX_POSTGRES_USER=postgres DEX_POSTGRES_HOST="localhost" DEX_LDAP_TESTS=1 DEBIAN_FRONTEND=noninteractive


install:
  - go get -u github.com/golang/lint/golint
  - sudo -E apt-get install -y --force-yes slapd time ldap-utils
  - sudo /etc/init.d/slapd stop


script:
  - make testall
  - ./scripts/test-k8s.sh

notifications:
  email: false
